# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8bb201162a051d3c6ed81161b7a64ee40014237dc26cccc24c069ede51fe4321a8e899e77507c0c4ff4a129be8f5f4481d39ae45703a29b53fce26f99e9fd01

test:
  secret_key_base: cad032f95d8381b5f75c4fc6a606792ec128c17ed4ff91777ec2f1c33c1523856edea796504db4439fb902c533a951eef5b7ea501e83265c8f713e2fec72e3e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
